function hm_load = f_loadmenu (user,label,cback)

%F_LOADMENU: Create load menu item
%
% Usage: hm_load = f_loadmenu (user,label,cback);
%
% Inputs: 
%          user  = string containing name of default file
%          label = menu label 
%          cback = callback string
% Outputs:
%          hm_load = handle to menu item

cback_load = ['caption = ''Select MAT file containing homework assignment''; '...
              'ver  = version; '...
              'u = get (hm_load,''Userdata''); '...
              'if all(ver(1:3) == ''6.1'') '...
              '    [user,path1] = uigetfile (''*.mat'',caption); '...
              'else '...
              '    [user,path1] = uigetfile (''*.mat'',caption,u); '...
              'end, '...
              'if ~isequal(user,0) '...
              '   old_path = pwd; '...
              '   cd (path1); '...
              '   load (user), '...
              '   cd (old_path), '...
              'end, '...
              cback];
 hm_load = uimenu (gcf,'Label',label,'Callback',cback_load,'Userdata',[user '.mat']);
 