function f_printmenu (han,drawstr)

%F_PRINTMENU: Create print menu item
%
% Usage: f_printmenu (g_module,han,plotstr) 
%
% Inputs:
%         han       = array of axis handles
%         drawstr   = string to redraw block diagram

hm_6 = uimenu (gcf,'Label','Print');
hm_61 = uimenu (hm_6,'Label','To printer','Callback','print -v');

cback2 = [
          '[ufname,upath] = uiputfile(''c:\\fdsp\\u_print.eps'',''Save As'');'...
          'if ufname == 0, return, end;'...
          'userprint = [upath ufname];'...
          'estring = sprintf (''print -depsc2 -noui %s'',userprint);'...
          'for i = 1 : 5, '...
          '   axes(han(i)), '...
          '   cla, '...
          '   axis off, '...
          'end, '...
          'eval(estring); '...
          'for i = 1 : 5, '...
          '   axes(han(i)), '...
          '   axis on, '...
          'end, '...
          drawstr ...
         ];
 hm_62 = uimenu (hm_6,'Label','To ecapsulated postscript file','Callback',cback2);

