% simulation for WCDMA handover
% made by Cao zhichao 
clear all
close all
parameters; %load parameters         % load parameters of simulation (generated by parameters.m)
Nodes;      %load users users        % load nodes' information (generated by Nodes.m)
global TOTAL_EVANT TOTAL_DROP
TOTAL_EVANT=0;
TOTAL_DROP=0;

global TOTAL_HANDOVER HANDOVER_DROP
TOTAL_HANDOVER=0;
HANDOVER_DROP=0;

global TIME
TIME=0;
global new_b_packet new_cbr
Packets=zeros(1,6);      %create an array to stroe every burst packet's information
packets_finnished=zeros(1,4);
CBRs=zeros(1,6);            %create an array to stroe the information of all cbr traffic
BS_utilization=zeros(simu_time,7);
step=0;
for t=1:simu_time       % make simulation loop for every second
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     doing traffic
   users=traffic_type(users,Cell_Num,N,p_idol,p_voice,p_video,ave_call_dur,ave_video_dur,voice_bit_rate,video_bit_rate,min_data_rate); %generate different types of traffic
    users=generate_burst(users, Cell_Num, N, average_burst_rate,burst_packet_size);  %generate burst traffic
    Packets=save_packet(Packets,users,burst_packet_size);    %save all burst packet in an array
    CBRs=save_cbr(CBRs,users);                      %save the information of cbr traffic                                            
    
    for k=1:ts_number   % go through the time slots in one sec
        TIME=TIME+1/ts_number;
        [users,Packets,CBRs,BS_utilization,packets_finnished]=process_all(packets_finnished,BS_utilization,CBRs,users,Packets,Cell_Num,N,available_sf,ts_number,min_data_rate,minimum_cbr_rate,t,simu_time);
    end
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  movement
    p_in_cell=users(:,5);  %Record current cell       
    users=move(users, Cell_Num, N, R, BS_location);     % make a move
    users=findcell(users, N, Cell_Num, R); %find current cell
    q_in_cell=users(:,5);            %Record current cell
    users=change_relative(users, Cell_Num, N, R, p_in_cell, q_in_cell, BS_location);  %change relative coordinates          
    users=is_inside(users, Cell_Num, N, R); %decide if the nodes are out of bounds
    
  for m=1:N*Cell_Num                % check if the node has made a handovered
       if p_in_cell(m)~=users(m,5)
          users(m,16)=1;            
       else
           users(m,16)=0;
       end
  end   
  TOTAL_HANDOVER=TOTAL_HANDOVER+size(find(users(:,16)==1 & users(:,10)~=0),1);  %calculate total handove calls;
  showpos(users, t, N, R, BS_location, Cell_Num);     % display the position of nodes
end


%simulation result:
if size(packets_finnished,1)==1
    Average_delay=0;
else
    Average_delay=sum(packets_finnished(2:end,3))/(size(packets_finnished,1)-1);
end
Average_delay
draw_figure(users,CBRs,packets_finnished,Average_delay,BS_utilization,simu_time)
